### ISSUE TITLE
Add an installer loading gif?

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron-api-demos#147]
Squirrel installers allow for a loading gif.

Currently it is configured to use: https://github.com/electron/electron-api-demos/blob/master/assets/img/loading.gif

We don't necessarily need an animated one but I wanted to see if people thought we needed something more than the current one.

For comparison, Atom uses this:

![](https://raw.githubusercontent.com/atom/atom/master/resources/win/loading.gif)

/cc @simurai

**Comment by Moonie68** [comment]
Hey, is it alright if I modify the Atom Loading gif for my app?
