### ISSUE TITLE
[feature-request] make executable instructions

### ISSUE THREAD

**Issue by dcrystalj** [electron/electron-api-demos#190]
I would love to see instructions how to make installer or pack in ```asar``` and distribute app.  I know its not related to main electron repository but its hard related to electron eco-system

**Comment by zeke** [comment]
This is indeed an important thing for electron developers to know, but it's out of the scope of the demo app, which exists primarily to familiarize users with Electron's APIs.

I would recommend these docs for learning more about `asar` and how to package and distribute your app:

- http://electron.atom.io/docs/tutorial/application-distribution/
- http://electron.atom.io/docs/tutorial/application-packaging/
