### ISSUE TITLE
Wrong path to invisible.html in communication with invisible windows example

### ISSUE THREAD

**Issue by iyedb** [electron/electron-api-demos#193]
Reproduced on Win7 and OS X, the path to invisible.html is wrong leading to the invisible window process being created and not destroyed and the factorial 100 is not returned.

![image](https://cloud.githubusercontent.com/assets/643030/15255100/4bafea3e-193a-11e6-94d7-6694c69f51c4.png)

**Comment by kevinsawicki** [comment]
Fixed by #194
