### ISSUE TITLE
Include example for using the remote module.

### ISSUE THREAD

**Issue by carlskii** [electron/electron-api-demos#208]
Is there an example for using the remote module in the this demo?  I can't seem to see it anywhere.

It would be good to add this to the communication section.

**Comment by jlord** [comment]
While there isn't a remote specific demo right now, many of the demos do use `remote`. For instance the Windows demos use `remote` to create new windows. Perhaps that can be helpful until a specific `remote` demo is added.

**Comment by jlord** [comment]
I'm going to close this out. We use `remote` in many of the existing demos so it is documented. If someone wants to add a demo specifically for remote it would be welcomed and they can open a PR ✨
