### ISSUE TITLE
Adding additional libraries to the renderer process

### ISSUE THREAD

**Issue by carlskii** [electron/electron-api-demos#211]
Hi, what would be the correct way to add additional JavaScript libraries to the Renderer process? E.g. jquery

**Comment by danhp** [comment]
You can leverage the fact that you have to access Node, so you can add a `require()` pointing the jQuery file similar to what is done in `index.html`:
https://github.com/electron/electron-api-demos/blob/master/index.html#L103

For future references, questions are best answered over at https://discuss.atom.io/c/electron where more people are likely to see them 😄
