### ISSUE TITLE
App demo is blank: locally on Windows 8, 10

### ISSUE THREAD

**Issue by IAMtheIAM** [electron/electron-api-demos#218]
- What operating system are you using? 
  Windows 10 pro x64
- What version of Node.js is on your system?
  Node LTS 4.4.4

When I clone, `npm install` and `npm start` the app, it opens the window, and its just blank. Devtools shows no markup at all. What is missing to make it install?

**Comment by jlord** [comment]
Hmm, that's strange. This should be all you need in order to launch. Are you getting errors in your terminal either when you `npm install` or after `npm start`?

**Comment by hlh1986** [comment]
Your opterating system  is not support this installion  program . change your computer opterating system to Window 8 pro x64

**Comment by jlord** [comment]
> Your opterating system is not support this installion program 

This app _does_ work with Windows 10 Pro. I've just tested it there with Node `4.4.5`

**Comment by hovancik** [comment]
@IAMtheIAM  

try to wait more time. in my case (os x), it does take around minute to see app's contents. it's blank window until then

**Comment by NoahDragon** [comment]
I'm using Win 10, and nodejs 4.4.5. Nothing popup after run the demo.

**Comment by jlord** [comment]
Does anyone get any errors in the console (or elsewhere) when they do this?

**Comment by jlord** [comment]
I am not able to reproduce this using Windows 10 Pro x64 with either Node LTS 4.5.0 or 6.5.0. I don't have a Windows 8 VM to test on however so can't report there.

**Comment by NoahDragon** [comment]
Mine is working on the latest Demo 1.1.0.

**Comment by Haacked** [comment]
> Mine is working on the latest Demo 1.1.0.

Thanks for following up!

@IAMtheIAM are you still running into problems?

**Comment by cuboicloide** [comment]
To start the app, you can run the following _(one line)_ command into your cmd:

`C:\Users\Francesco\Documents\GitHub\electron-api-demos\node_modules\electron\dist\electron.exe C:\Users\Francesco\Documents\GitHub\electron-api-demos\main.js`

Obviously, change the path in order to match your own electron-api-demos folder.

**Comment by IAMtheIAM** [comment]
Strange but it appears to be working now. I tried using fresh install of windows 10 x64, node 6.9.1 LTS and everything works fine. On my other computer where the original issue was, I havent yet reconfirmed. So I'll close this until I test on that computer again, if it persists I'll reopen. Thanks for following up.

**Comment by AskKN** [comment]
Its very simple, go to your user folder in Windows. Then AppData. Then Roaming. Then delete the folder Electron API Demos. Its done. Go back to the folder of original binary Electron API Demos and open the Electron API Demos.exe app.

**Comment by Welding-Torch** [comment]
I'm having the same problem.

Node Package Manager Version:  8.5.5
Node Version: 17.8.0


> To start the app, you can run the following _(one line)_ command into your cmd:
> 
> `C:\Users\Francesco\Documents\GitHub\electron-api-demos\node_modules\electron\dist\electron.exe C:\Users\Francesco\Documents\GitHub\electron-api-demos\main.js`
> 
> Obviously, change the path in order to match your own electron-api-demos folder.

Tried this, didn't work
