### ISSUE TITLE
Screen size inaccurate.

### ISSUE THREAD

**Issue by cairinmichie** [electron/electron-api-demos#221]
My screen size is 1920x1080, but the API Demo app says it is 1920x1050.

Operating system:

* Windows 10 Pro

Node.js version:

* Node.js 5.7.0 (x64)

![screen1](https://cloud.githubusercontent.com/assets/10084084/15894745/dfd12834-2d87-11e6-9a46-9627dcf4315b.jpg)

**Comment by cairinmichie** [comment]
I think it may be due to the taskbar height. Does `workAreaSize` include the taskbar? 

`const size = electronScreen.getPrimaryDisplay().workAreaSize`

**Comment by jlord** [comment]
> I think it may be due to the taskbar height. Does workAreaSize include the task bar?

Ah, yeah, you're right. There is `workAreaSize` which is the available screen real estate and then `.size` which provides the raw dimensions of the screen.

This should be more clear and I'll make a pull request 👍
