### ISSUE TITLE
Error while running npm-install

### ISSUE THREAD

**Issue by greenleafone7** [electron/electron-api-demos#233]
While trying to run `npm-install` I kept getting this error.

```
50 error Windows_NT 6.1.7601
51 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
52 error node v0.12.0
53 error npm  v2.5.1
54 error code ETARGET
55 error notarget No compatible version found: electron-windows-store@'>=0.3.0 <0.4.0'
55 error notarget No valid targets found.
55 error notarget Perhaps not compatible with your version of node?
55 error notarget This is most likely not a problem with npm itself.
55 error notarget In most cases you or one of your dependencies are requesting
55 error notarget a package version that doesn't exist.
56 verbose exit [ 1, true ]
```

I do not know if this is an issue due to my machine or is it something that is worth reporting, but I am doing so anyway. Please advise whether this is an actual bug with the code or not.

Thanks.

**Comment by zeke** [comment]
It looks like there is indeed a 0.3.0 version of that package which which satisfies the `'>=0.3.0 <0.4.0` range, so that's not the issue:

```
$ npm i -g json && curl -s http://registry.npmjs.org/electron-windows-store | json versions | json -k
[
  "0.1.0",
  "0.1.1",
  "0.1.2",
  "0.2.1",
  "0.2.2",
  "0.2.3",
  "0.2.4",
  "0.2.5",
  "0.2.6",
  "0.2.7",
  "0.3.0",
  "0.4.0",
  "0.4.1",
  "0.4.2",
  "0.5.0"
]
```

```
$ npm i -g trymodule && trymodule semver

> semver.satisfies('0.3.0', '>=0.3.0 <0.4.0')
true
```

Ah, I think I found it: https://github.com/felixrieseberg/electron-windows-store/blob/62ed6d4a904824f3740c0631dd8e57e6ca312d79/package.json#L25-L27

The package requires node 4 or greater. You're running node 0.12. Are you able to upgrade?

**Comment by greenleafone7** [comment]
I see, then this has nothing to do with the code itself. I shall upgrade to the suggested version, thank you for the heads up.
