### ISSUE TITLE
ElectronAPIDemos.exe can't start error message

### ISSUE THREAD

**Issue by hwaynefair** [electron/electron-api-demos#236]
Error when starting exe: "This program can't start because node.dll is missing from your computer"

windows 10
4.2.3

**Comment by zeke** [comment]
Hi @hwaynefair. Did you build the app from source or download the exe from somewhere?

**Comment by hwaynefair** [comment]
Downloaded from electron website.
Then built from GitHub and works fine.
Thanks!

**Comment by zeke** [comment]
This might shed some 💡 

https://github.com/electron-userland/electron-packager/issues/330
