### ISSUE TITLE
Register a custom protocol so we can deep link to demos.

### ISSUE THREAD

**Issue by zeke** [electron/electron-api-demos#238]
I keep telling people "there's a demo for that". It would be cool if we could link directly to specific demos, like:

``` html
<a href="electron-api-demos://context-menu">View the Context Menu demo</a>
```

**Comment by simonkaspersen** [comment]
Is this still desirable to achieve? And if yes, some more thoughts?

**Comment by zeke** [comment]
Yeah I still think this would be cool.

It would require registering a custom protocol handler: https://electron.atom.io/docs/api/protocol/

**Comment by simonkaspersen** [comment]
I guess we should wait for #271 with the electron-fix?

**Comment by zeke** [comment]
Yeah I think you're right. There's a WIP fix for it at https://github.com/electron/electron-api-demos/pull/275 that is waiting on https://github.com/electron/electron/pull/8052

**Comment by Baonui9999** [comment]
เภน

**Comment by zeke** [comment]
> เภน

?

**Comment by codebytere** [comment]
Implemented!
