### ISSUE TITLE
mac electron change icon?

### ISSUE THREAD

**Issue by caishengmao** [electron/electron-api-demos#239]
"pack-mac": "electron-packager . --asar --asar-unpack=protocol-link.html --overwrite --platform=darwin --arch=x64 --icon=assets/app-icon/mac/app.icns --prune=true --out=out --osx-sign.identity='Developer ID Application: GitHub' --extend-info=assets/mac/info.plist", This demo change icon to another, why I can't change?

**Comment by jlord** [comment]
Hi! The line you have pasted points `electron-packager` to the location of the `.icns` icon file to be used on macOS. I'm not sure I understand your question, are you wanting to know how to change the icon in your own Electron app?

**Comment by jlord** [comment]
Closing until more information is added ✨
