### ISSUE TITLE
安装不上

### ISSUE THREAD

**Issue by hanwenbo** [electron/electron-api-demos#240]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.2.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ElectronAPIDemos@1.1.0~prestart: ElectronAPIDemos@1.1.0
6 silly lifecycle ElectronAPIDemos@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle ElectronAPIDemos@1.1.0~start: ElectronAPIDemos@1.1.0
8 verbose lifecycle ElectronAPIDemos@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ElectronAPIDemos@1.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/hanwenbo/electron-api-demos/node_modules/.bin:/usr/local/Cellar/node/6.2.2/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle ElectronAPIDemos@1.1.0~start: CWD: /Users/hanwenbo/electron-api-demos
11 silly lifecycle ElectronAPIDemos@1.1.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle ElectronAPIDemos@1.1.0~start: Returned: code: 1  signal: null
13 info lifecycle ElectronAPIDemos@1.1.0~start: Failed to exec start script
14 verbose stack Error: ElectronAPIDemos@1.1.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ElectronAPIDemos@1.1.0
16 verbose cwd /Users/hanwenbo/electron-api-demos
17 error Darwin 15.5.0
18 error argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error ElectronAPIDemos@1.1.0 start: `electron .`
22 error Exit status 1
23 error Failed at the ElectronAPIDemos@1.1.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ElectronAPIDemos package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ElectronAPIDemos
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ElectronAPIDemos
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jlord** [comment]
Hi! Could you tell us more about what you did before getting this error and what version of macOS you are on?

**Comment by jlord** [comment]
Feel free to re-open with more information.
