### ISSUE TITLE
Running /tests/

### ISSUE THREAD

**Issue by violinner** [electron/electron-api-demos#242]
* What operating system are you using? Windows 7
* What version of Node.js is on your system? 5.0.0

How can I run the test in electron-api-demos/tests/index.js ?

npm test

runs a mocha test, which fails with a message (below).
Do you have any advice on how to run correctly?
Is the Electron GUI supposed to come up?

Thanks!

demo app
    1) "before all" hook
  0 passing (30s)
  1 failing
  1) demo app "before all" hook:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (C:\[my-path]\electron-api-demos\node_modules\mocha\lib\runnable.js:226:19)

**Comment by violinner** [comment]
What is needed to run a spectron test on this build?
Does something have to be run before npm test?

**Comment by jlord** [comment]
I'm not sure what is causing this problem and I'm not able to reproduce it because I don't have Windows 7. If you `npm install` and then `npm test` the tests should begin. The app options and goes through the motions in the spec and the results are put into your console.

**Comment by violinner** [comment]
There is a problem installing electron-chromedriver 1.0.0.

spectron v 3.2.3 depends on electron-chromedriver 1.2.1, and this combination will install.
The test, however will not work on spectron 3.2.4.

Is there a change to the test code, or other node module versions that would allow this example to run the tests using spectron v 3.2.3 or v 3.2.4?

**Comment by violinner** [comment]
How can I debug the problem running the test?
Is the GUI for the electron app supposed to pop up?
What process is supposed to cause this, and does it have a debug log setting?
Something, i.e., "demo app "before all" hook" is timing out waiting -- for what?

**Comment by hovancik** [comment]
@jlord @violinner 

I have same problem: 

OS X 10.11.5
node v6.2.2

`Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.`

**Comment by hovancik** [comment]
so it's node version. updating to 6.3.0 works

**Comment by etiennejcharles** [comment]
I tried a try catch statement on my windows machine for that on line:20 in tests/index.js
```
const productName = require('../package').productName;
try {
   const userDataPath = path.join(process.env.HOME, 'Library', 'Application Support', productName);
} catch (error) {
   throw error
}
```

And the returned error given to me is the following

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at removeStoredPreferences (C:\Users\etienne-joseph.charl\Desktop\electron-api-demos\tests\index.js:22:33)
    at Context.<anonymous> (C:\Users\etienne-joseph.charl\Desktop\electron-api-demos\tests\index.js:102:5)
    at callFn (C:\Users\etienne-joseph.charl\Desktop\electron-api-demos\node_modules\mocha\lib\runnable.js:326:21)
    at Hook.Runnable.run (C:\Users\etienne-joseph.charl\Desktop\electron-api-demos\node_modules\mocha\lib\runnable.js:319:7)
    at next (C:\Users\etienne-joseph.charl\Desktop\electron-api-demos\node_modules\mocha\lib\runner.js:298:10)
    at Immediate.<anonymous> (C:\Users\etienne-joseph.charl\Desktop\electron-api-demos\node_modules\mocha\lib\runner.js:320:5)
````

Seems like the path is no good on windows. 

Somewhat using something like :
```
process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
```
Would be the solution
But don't have a clue how to fix this, I'm still discovering node, smells like PR.
