### ISSUE TITLE
`powerSaveBlocker` method example

### ISSUE THREAD

**Issue by amilajack** [electron/electron-api-demos#245]
`powerSaveBlocker` doesn't seem to work for me. I used the example in the docs but `powerSaveBlocker` is imported as undefined. I'm wondering if some examples could be provided in this repo. Thanks!

**Comment by zeke** [comment]
@jlord added `powerSaveBlocker` to the playback app a while ago. Here's the code for that: https://github.com/mafintosh/playback/blob/16fcfe1ff3a53a0dc5a7875b53bf3cda7f526d59/app.js#L9

If you're still stuck, can you share a snippet of the code you're using?

**Comment by amilajack** [comment]
I've fixed it. I need to import `remote` from `electron` because I was using it in the renderer process.

**Comment by jlord** [comment]
> I've fixed it.

Sweet! 

> I'm wondering if some examples could be provided in this repo.

We thought about including it but it's hard to _demo_ because we'd need the power change on the user's system 🔋
