### ISSUE TITLE
Virus Detected in files while npm install

### ISSUE THREAD

**Issue by lugaid13** [electron/electron-api-demos#249]
* What operating system are you using? 
Windows 8.1
* What version of Node.js is on your system?
4.4.7

While performing npm install, I get a warning message from the Antivirus scan for this file
electron-api-demos\node_modules\electron-winstaller\vendor\WriteZipToSetup.exe
Detected as a trojan Artemis!93D2D59A3747

**Comment by felixrieseberg** [comment]
The signature of a valid installer and a malware installer are really similar, but we already confirmed that the files matched are a-ok. It's kind of difficult to point out where exactly the blame should be, but bottom line is that that `electron-winstaller` does not contain any viruses or trojans...

**Comment by lugaid13** [comment]
Thanks for the quick response.
Hopefully this information will be useful for future users
