### ISSUE TITLE
Warning: Trojan and virus inside "spectron" module.

### ISSUE THREAD

**Issue by mars-lander** [electron/electron-api-demos#250]
Be careful guys and please warn users on README file about this.
DO NOT USE THAT MODULE.
Here is list of Trojan and Riskwares:

Trojan.Win32.Generic!BT
W32.Clodb96.Trojan.3010
Trojan.Ebowla
W32/Trojan.CNQO-8612
Trojan.Ebowla.d
Riskware ( 0040eff71 )
Riskware ( 0040eff71 )
Trj/CI.A
Trojan.Win32.Z.Ebowla.1744384[h]

**Comment by MarshallOfSound** [comment]
@mars-lander Please track this upstream in #93

It is a false positive, we simply need to determine what is causing it.  Maybe you can provide that issue with more details as to exactly which file is causing these false positives and all the details your AV program gives you
