### ISSUE TITLE
Consider replacing `electron-json-storage` with `electron-config`

### ISSUE THREAD

**Issue by zeke** [electron/electron-api-demos#251]
When we first started storing user state in the app, we tried localStorage, but that wasn't great because localStorage is only persisted to disk if the app exits "cleanly". `^C` is not a clean exit, so state is lost when you're in development.

I googled around and ended up finding `electron-json-storage`. It worked for our needs, but wasn't ideal because of its asynchronous API.

[electron-config](http://ghub.io/electron-config) is a newish module with a synchronous API that's easier to reason about.

Here's an example of the before and after code when switching: https://github.com/cheshire137/gh-notifications-snoozer/commit/90f4231d294b75252c5fe0536185ce0189c33be6?diff=split

cc @cheshire137

**Comment by tiemevanveen** [comment]
I switched my electron project over to `electron-config` and it works great! I'm only [not entirely sure](https://github.com/sindresorhus/electron-config/issues/4#issuecomment-268971969) if it's fully meant to be used as a store rather than just for the occasional config.

**Comment by zeke** [comment]
Thanks for you input, @tiemevanveen. For the purposes of this demo app (and probably most Electron apps), synchronously writing small configuration files to disk is not a concern. We're only saving a handful of things like "currently active menu" state, so writes don't occur very frequently.

While we're on the topic, I recently discovered https://github.com/nathanbuchar/electron-settings which looks pretty interesting. It's async by default with promises, but all the methods have sync versions too. There's also this interesting [observe() method](https://github.com/nathanbuchar/electron-settings/blob/master/docs/methods.md#observe).. not really sure what I'd use that for but good to know that it exists.

cc @nathanbuchar

**Comment by nathanbuchar** [comment]
@zeke, thanks for the shout out!

For what it's worth I wish I had made electron-settings simpler and without Promises but callbacks instead. electron-config is more or less what I wanted to do before I got a bit carried away, but the `observe` method in electron-settings is nice and can come in handy :) Atom's internal settings manager also has an `observe` method built in, which is what electron-settings was inspired from.

Part of me wants to rewrite a v3 version, but with the amount of downloads it has right now I'd be afraid of breaking people's code :\

**Comment by zeke** [comment]
> the observe method in electron-settings is nice and can come in handy

For what purpose are you using it?

> afraid of breaking peoples' code

That's what major versions are for! :)

**Comment by MarshallOfSound** [comment]
> the observe method in electron-settings is nice and come in handy

Yeah, when I wrote my own Settings handler (back in the day) one of the only reasosn I did so is so I could add a "change" watcher.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/utils/Settings.js#L35

> For what purpose are you using it?

Personally I use it for React purposes.  I have a wrapper component that on mount starts watching for settings changes and passes through the settings values as a prop to the child component.  This makes things like theming super easy, you simply set the setting somewhere and all your observing components just update 👍

**Comment by nathanbuchar** [comment]
@MarshallOfSound @zeke 

v3.0.0 is out :) drastically simpler and more dynamic. And of course, I kept the change watcher functionality!

**Comment by zeke** [comment]
>  electron-settings v3.0.0 is out!

Nice. So it's synchronous by default now?

**Comment by nathanbuchar** [comment]
It's only synchronous now. One of my gripes about <v3 was the technical headaches caused by asynchronous saving and promises. One common issue is that it's not unheard for a user to run `settings.set()` in two different places at the same time, and then run into conflicts and corrupted data. I suppose a solution would be to add some sort of queueing system, but that's going down quite a rabbit hole.

Really what I wanted ElectronSettings from the start to be was an easy framework to just read, write, and delete settings, and that's what I believe it is now! And of course, with the handy addition of the settings watcher :)

**Comment by zeke** [comment]
Cool. Do you have any interest in updating this demo app to use the new `electron-settings`? If not, no worries. I can get to it at some point.

**Comment by nathanbuchar** [comment]
Yeah! I can take care of it. Thanks for the consideration :-)
