### ISSUE TITLE
Golang talking to electron

### ISSUE THREAD

**Issue by joeblew99** [electron/electron-api-demos#253]
* What operating system are you using? 
Osx
* What version of Node.js is on your system?
6

I am trying to convey all of the api demos so that all the UX actions can be initiated from golang.

Does anyone have any tips / samples ?

**Comment by jlord** [comment]
@joeblew99 we haven't experimented with that on our team. I'm going to close out here since it's not a bug in this app; you'll likely find more resources in the forum: https://discuss.atom.io/c/electron.
