### ISSUE TITLE
pack-win hangs when project is placed directly top level folder 

### ISSUE THREAD

**Issue by asRIA** [electron/electron-api-demos#256]
Windows 10,  Node 6.4.0

```
C:
git clone git@github.com:electron/electron-api-demos.git elapi && cd eltest
npm install
npm run-script pack-win

> ElectronAPIDemos@1.1.0 pack-win C:\eltest
> electron-packager . ElectronAPIDemos --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=ia32 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'
```
After that, application hangs and has to be killed.

After tracking down this issue it looks like: electro-packager->get-package-info extension jumps into not terminated loop. Unfortunately I wasn't able to track down if it was due `electron-api-demos` configuration or due error in submodule's logic.

Placing the same project to a subfolder makes this step work. 

I've tested `electron-packager` on some other project placed directly in partition folder and it worked.

Edit:
1 0000 0000 (b) issue 🎂 🎆

**Comment by jlord** [comment]
I wasn't able to reproduce this with:

- Windows 10
- Node 4.50

![npmrunpackwin](https://cloud.githubusercontent.com/assets/1305617/18322163/1d16188a-74e6-11e6-9875-993b2c04f440.png)

Could it possibly be a Node 6 issue?

**Comment by jlord** [comment]
I also wasn't able to reproduce this after installing Node 6.5.0 😕 

![node65](https://cloud.githubusercontent.com/assets/1305617/18322712/e5a562e0-74e8-11e6-8fe0-67a065a77c02.png)

**Comment by asRIA** [comment]
@jlord you have to place a project directly in `C:\` path (or any other disc letter.

**Comment by jlord** [comment]
@asRIA Oh, whoops, sorry, I had that in my head then totally went off and forgot that part 😄 

I cloned this repo directly into `C:\` and was able to package:

![cdir](https://cloud.githubusercontent.com/assets/1305617/18327239/720d9490-74fe-11e6-8394-42c439d5812e.png)

In your original comment you clone into `elpais` and then `cd eltest`, not sure if I'm missing something here but shouldn't you `cd elpais`?

**Comment by asRIA** [comment]
@jlord 
My bad, I mean it should be twice the same name. I just shorten a name to remove `-` form it. (just in case) 

It looks like it works for you, have you tried node 6.5?

**Comment by asRIA** [comment]
@jlord Apparently I can't reproduce it anymore. Not sure why, because I didn't change my setup. Nevertheless thank you for checking this out! 👍

**Comment by jlord** [comment]
@asRIA Awesome, thanks!
