### ISSUE TITLE
add a Chinese version

### ISSUE THREAD

**Issue by fuchao2012** [electron/electron-api-demos#259]
sorry to open a issue not a PR.

wants fellows to check again.

https://github.com/fuchao2012/zh-cn-Electron-API-Demos

**Comment by jlord** [comment]
Hi!

I'm not sure I understand your question or issue? Have you created a translated version of the app?

**Comment by fuchao2012** [comment]
hi , @jlord yep. I had translated the app into chinese.

**Comment by jlord** [comment]
@fuchao2012 Cool, thanks for that! I'll add a link to your project in the `readme` here.
