### ISSUE TITLE
Release process hangs on Heroku deployment step

### ISSUE THREAD

**Issue by zeke** [electron/electron-api-demos#267]
Output is stuck at this:

```
Zipping Electron API Demos.app to electron-api-demos-mac.zip
Zipping ElectronAPIDemos-win32-ia32 to electron-api-demos-windows.zip
Zipping Electron API Demos-linux-x64 to electron-api-demos-linux.zip
Creating new draft release
Uploading electron-api-demos-mac.zip as release asset
Uploading electron-api-demos-windows.zip as release asset
Uploading electron-api-demos-linux.zip as release asset
Uploading RELEASES as release asset
Uploading ElectronAPIDemosSetup.exe as release asset
Uploading ElectronAPIDemos-1.2.0-full.nupkg as release asset
Publishing release
Deploying to heroku
```

When I try to access the app's config in another tab:

```
❯ heroku config -a github-electron-api-demos
 ▸    Invalid credentials provided.
Enter your Heroku credentials.
Email: 
```

So I think the process is just hanging on this stdin thing.

@kevinsawicki any thoughts on how to make this fail when not logged in (or even better, ask for creds on the fly)? Maybe a `heroku whoami` check before?

**Comment by kevinsawicki** [comment]
> any thoughts on how to make this fail when not logged in (or even better, ask for creds on the fly)? Maybe a heroku whoami check before?

Nope, haven't really done much work with the `heroku` CLI before. Adding an early check somehow seems fine to me.
