### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by linyi-xia** [electron/electron-api-demos#274]
* What operating system are you using?  Win10
* What version of Node.js is on your system? N/A

When I try to extract the file, it alerted me that Trojan has been detected in the zip file....

**Comment by MarshallOfSound** [comment]
> When I try to extract the file

What file and what anti-virus software.  It is 100% a false positive FYI

**Comment by linyi-xia** [comment]
I downloaded electron-api-demos-windows.zip and it just alerted me that trojan detected.
