### ISSUE TITLE
Getting errors while doing npm install for the demo app

### ISSUE THREAD

**Issue by Anuj16** [electron/electron-api-demos#280]
* What operating system are you using?
 Windows 8
* What version of Node.js is on your system?
6.9.2

[npm-debug.txt](https://github.com/electron/electron-api-demos/files/643675/npm-debug.txt)

**Comment by kevinsawicki** [comment]
Are you able to run `npm install electron@1.4.12` by itself?

**Comment by Anuj16** [comment]
No, i am getting the exact same error.

**Comment by kevinsawicki** [comment]
@Anuj16 can you include the output from running `npm install @electron@1.4.12`?

**Comment by Anuj16** [comment]
> electron@1.4.12 postinstall C:\Windows\system32\node_modules\electron
> node install.js

C:\Windows\system32\node_modules\electron\install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shivratna\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron@1.4.12"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by kevinsawicki** [comment]
> Error: read ECONNRESET

It looks like your machine is having issues connecting to github.com where the Electron binaries are downloaded from. Are you using a proxy?

Are you able to download https://github.com/electron/electron/releases/download/v1.4.12/electron-v1.4.12-win32-ia32.zip directly?

Can you include the output of `npm config get proxy`?

**Comment by Anuj16** [comment]
>> Are you using a proxy?
No
>> Are you able to download https://github.com/electron/electron/releases/download/v1.4.12/electron-v1.4.12-win32-ia32.zip directly?
No, it falis after saying network error after some time.

 >> npm config get proxy
null

**Comment by chenzhq** [comment]
I hava the same error. But my OS is Ubuntu(NodeJS in Windows is terrible)

**Comment by xiguaaxigua** [comment]
same error in Mac, but run `npm install` again save it.

**Comment by zeke** [comment]
As noted above, the `ECONNRESET` error is indicative of a network problem. When you get this error, the best thing to do is try again later or use another network.
