### ISSUE TITLE
create desktop shortcut not working as expected

### ISSUE THREAD

**Issue by nidhir-systango** [electron/electron-api-demos#283]
Hi, i have copied your auto-updater code for crating shortcut but the name of the shortcut is taking as electron even if my app name is something specific.

main.js-
 switch (process.argv[1]) {
  case '--squirrel-install':
    autoUpdater.createShortcut(function () { app.quit() })
    break
  case '--squirrel-uninstall':
    app.removeAsDefaultProtocolClient('onepgr-share')
    autoUpdater.removeShortcut(function () { app.quit() })
    break
  case '--squirrel-obsolete':
  case '--squirrel-updated':
    app.quit()
    break
  default:  
}

auto-updator.js
exports.createShortcut = function (callback) {
  spawnUpdate([
    '--createShortcut',
    path.basename(process.execPath),
    '--shortcut-locations',
    'Desktop'
  ], callback)
}

maybe some cache issue,but i have checked it after restarting my system also."
Any help?
Thanks in advance.

**Comment by MarshallOfSound** [comment]
This isn't an issue with the API demos but I'll help ya out anyway 😆 

Basically the shortcut name is generated from the metadata of the `.exe` file that you make, if you are using `electron-packager` you can set this metadata with this API option.

https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#win32metadata
