### ISSUE TITLE
Split up tests a bit 

### ISSUE THREAD

**Issue by teameh** [electron/electron-api-demos#285]
I think it's a good idea to split up `tests/index.js` into `tests/index.js` and a `tests/setup.js`. That way it's clear for new users what the setup and what the actual test code is, and it also allows them to copy paste the setup code into their own project for reuse.

Do you agree and would you like a PR for this?

**Comment by zeke** [comment]
> Do you agree and would you like a PR for this?

Yes 👍

**Comment by codebytere** [comment]
Resolved by https://github.com/electron/electron-api-demos/pull/342
