### ISSUE TITLE
Please add some  example loading local html to existing webview demo 

### ISSUE THREAD

**Issue by emptist** [electron/electron-api-demos#289]
I've tried to find information in docs and from stackoverflow and found very little and am not so lucky to put it right to work.

Could you add some demo on how to load from local html and open devtools, etc. ?

**Comment by victorhsn** [comment]
Hi @emptist, What do you want to load from local? And if you want to open the devtools you can add at entry point file(eg: main.js) the following statement BrowserWindow.webContents.openDevTools().

;)

**Comment by zeke** [comment]
@emptist your best bet is to probably start with the [electron/electron-quick-start](https://github.com/electron/electron-quick-start) app. It loads and HTML file from disk, and also has a section about enabling devtools.

Other resources to check out:

- [electron.atom.io/docs](http://electron.atom.io/docs) - all of Electron's documentation
- [electron.atom.io/community/#boilerplates](http://electron.atom.io/community/#boilerplates) - sample starter apps created by the community
- [electron/simple-samples](https://github.com/electron/simple-samples) - small applications with ideas for taking them further
- [hokein/electron-sample-apps](https://github.com/hokein/electron-sample-apps) - small demo apps for the various Electron APIs

**Comment by emptist** [comment]
Thanks and I've managed to use webview with local file.

**Comment by zeke** [comment]
Nice. Thanks for following up. 👍
