### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by chadbr** [electron/electron-api-demos#293]
There's no place to say "thanks" -- so I'll do it here.

This project is fantastic - thanks to whomever started / contributed to it. 

I wish I had found it a few months back 👍

**Comment by zeke** [comment]
Thanks, @chadbr!

Here's the first commit: https://github.com/electron/electron-api-demos/commit/84fef597aed958fec3405daa6292aa05215063eb 

And more contributors https://github.com/electron/electron-api-demos/graphs/contributors :)
