### ISSUE TITLE
Error in nmp install on Ubuntu

### ISSUE THREAD

**Issue by enricjaen** [electron/electron-api-demos#303]
I get this error:

> ElectronAPIDemos@1.3.0 start /home/enric/Downloads/electrondemo/electron-api-demos
> electron .

/home/enric/Downloads/electrondemo/electron-api-demos/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/enric/Downloads/electrondemo/electron-api-demos/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/enric/Downloads/electrondemo/electron-api-demos/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 3.19.0-82-generic
npm ERR! argv "/usr/bin/nodejs" "/home/enric/Downloads/node-v6.10.1-linux-x64/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ElectronAPIDemos@1.3.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ElectronAPIDemos@1.3.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ElectronAPIDemos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ElectronAPIDemos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ElectronAPIDemos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/enric/Downloads/electrondemo/electron-api-demos/npm-debug.log

**Comment by 50Wliu** [comment]
> Electron failed to install correctly, please delete node_modules/electron and try installing again

**Comment by enricjaen** [comment]
same result. I reinstalled electron and I get same error
