### ISSUE TITLE
APPCRASH on Windows 2008 SP2, thanks

### ISSUE THREAD

**Issue by tonychen0716** [electron/electron-api-demos#306]
SHELL32.dll!GetCurrentProcessExplicitAppUse

错误应用程序 ElectronAPIDemos.exe，
版本 1.4.1.0，
时间戳 0x57e3afac，
错误模块 SHELL32.dll!GetCurrentProcessExplicitAppUse，
版本 6.0.6002.18005，
时间戳 0x49e03824，
异常代码 0xc0000139，
错误偏移量 0x0006f04e， 
进程 ID 0x784c，
应用程序启动时间 0x01d2aebad08bca81。

**Comment by bysslord** [comment]
Does you solve the problem?

**Comment by tonychen0716** [comment]
no
