### ISSUE TITLE
My node is broken, or what?

### ISSUE THREAD

**Issue by wangcunlu1** [electron/electron-api-demos#310]
![default](https://cloud.githubusercontent.com/assets/20310872/26278163/dd72f55e-3dc6-11e7-9d02-9c48e1e07e90.PNG)
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'installer' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose stack Error: missing script: installer
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd C:\Users\someone\Desktop\electron-api-demos-master\script
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "installer"
8 error node v6.10.2
9 error npm  v3.10.10
10 error missing script: installer
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

 tell me how to solve it, please！！！

**Comment by Siilwyn** [comment]
It's because you execute `npm run installer` which in turn tries to run the not existing task `installer`. You can see the available tasks in the `package.json` scripts array or by executing `npm run`.

**Comment by wangcunlu1** [comment]
@Siilwyn 
![default](https://cloud.githubusercontent.com/assets/20310872/26278291/85e9c454-3dc9-11e7-9369-e05d091dfd53.PNG)

**Comment by wangcunlu1** [comment]
@Siilwyn 
![default](https://cloud.githubusercontent.com/assets/20310872/26278331/6aaebf22-3dca-11e7-88ce-061e3ea26563.PNG)

**Comment by wangcunlu1** [comment]
I Google
![default](https://cloud.githubusercontent.com/assets/20310872/26278370/61235282-3dcb-11e7-815e-112d37f408d3.PNG)
# **Still not solved**

**Comment by Siilwyn** [comment]
There is still no `installer` script/task... You're probably confused with `npm run package:installer`.

**Comment by wangcunlu1** [comment]
@Siilwyn
Wow, I actually ignored the NPM run-script document. Thank you for your help. I finally got it.
