### ISSUE TITLE
Package mac app installer

### ISSUE THREAD

**Issue by jacktang** [electron/electron-api-demos#313]
Hello,

I clone code from this repo and try to build mac installer by run `npm run package:mac`. It hangs and I don't where the building logs. The whole output:

```
22:00 $ npm run package:mac

> ElectronAPIDemos@1.3.0 package:mac /Users/jacktang/Code/electron-api-demos
> electron-packager . --overwrite --platform=darwin --arch=x64 --out=out --icon=assets/app-icon/mac/app.icns --osx-sign.identity='Developer ID Application: GitHub' --extend-info=assets/mac/info.plist

Packaging app for platform darwin x64 using electron v1.6.8
```

* What operating system are you using? 
macOS Sierra 10.12.5
* What version of Node.js is on your system?
v7.3.0

**Comment by codebytere** [comment]
This should be resolved on more recent versions.
