### ISSUE TITLE
Links to apple and Microsoft never last very long - 

### ISSUE THREAD

**Issue by HeilTec** [electron/electron-api-demos#320]
* What operating system are you using? N/A (irrelevant)
* What version of Node.js is on your system? N/A (irrelevant)

![image](https://user-images.githubusercontent.com/2696244/29272035-a19f14b0-80fe-11e7-8efd-5e6be732410d.png)

Of the 3 links to documents of OS keyboard, only Linux is still viable

`<a class="u-exlink" href="https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Keyboard.html">macOS</a>`

`<a class="u-exlink" href="http://windows.microsoft.com/en-us/windows-10/keyboard-shortcuts">Windows</a>`

`<a class="u-exlink" href="https://developer.gnome.org/hig/stable/keyboard-input.html.en">Linux</a>`

At current time Microsoft still redirect to the relevant article found at: [Keyboard shortcuts in Windows](https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts)
(https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts)

Apple on the other hand lands you at https://developer.apple.com/macos/human-interface-guidelines/overview/themes/ which is close but no cigar.
The needed info is but one click away at [Input and Output](https://developer.apple.com/macos/human-interface-guidelines/input-and-output/keyboard/) 
(https://developer.apple.com/macos/human-interface-guidelines/input-and-output/keyboard/)

A suggestion is to add the actual headlines of the articles. This will let users confirm easily if the link worked, and aid finding the docs when links grow stale.

**Comment by codebytere** [comment]
Will be fixed by https://github.com/electron/electron-api-demos/pull/344
