### ISSUE TITLE
npm intall error on Mac

### ISSUE THREAD

**Issue by Pgyer** [electron/electron-api-demos#322]
log：
`Error: connect ETIMEDOUT 54.231.120.35:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.6.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
taojiujiudeMacBook-Pro:electron-api-demos Tao9jiu$ node ==version
module.js:491
    throw err;
    ^

Error: Cannot find module '/my/DeskApplication/study/electron-api-demos/==version'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3`

node: v8.4.0
npm: 5.3.0
electron: 1.7.5

**Comment by mxy2316868975javascript** [comment]
me too !

**Comment by codebytere** [comment]
Are you sure you're not behind a corporate firewall?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
