### ISSUE TITLE
Cannot read property 'BrowserWindow' of undefined

### ISSUE THREAD

**Issue by abelardolg** [electron/electron-api-demos#326]
* What operating system are you using? 
MAC OS X 10.11.6 (15G1004)
* What version of Node.js is on your system?
8.2.1

I run this demo and all examples worked.

I copied the code of the first example ("create and manage windows") inside my "main.js" but it didn't work.
![captura de pantalla 2017-10-03 a las 9 41 19](https://user-images.githubusercontent.com/22522883/31115625-5ebe23ba-a823-11e7-85e1-476c11ee8795.png)

What's wrong?

Kindest regards,
Abelardo.

**Comment by codebytere** [comment]
If you look at the demos, you'll see that the header for that code says *Renderer Process* and thus should be put in `renderer.js`.
