### ISSUE TITLE
478 error Failed at the husky@0.14.3 install script 'node ./bin/install.js'.

### ISSUE THREAD

**Issue by anazodo** [electron/electron-api-demos#327]
* What operating system are you using? 
Ubuntu 16.04 LTS
* What version of Node.js is on your system?
nodejs --version
v4.2.6

[npm-debug.log](https://github.com/electron/electron-api-demos/files/1366281/npm-debug.log)

**Comment by anazodo** [comment]
I ran int this bug when I tried to build the Demo. I wanted to learn what the API is all about and how to use it. Is there any other way I can learn how use the API?

I see this file:
....Demos/node_modules/electron/install.js

but, from the log, it is looking for bin/install.js:

log has:
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! husky@0.14.3 install: node ./bin/install.js
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the husky@0.14.3 install script 'node ./bin/install.js'.

Is it looking for the install.js file in the wrong place?

**Comment by zeke** [comment]
Can you start in a fresh directory and show the commands you're using to get to this error?

You may also want to take a look at the [FAQ](https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron) to make sure you're installing electron properly, and also make sure you're [npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) are set properly.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
