### ISSUE TITLE
How to generate a setup installation steps like normal desktop when are being installed

### ISSUE THREAD

**Issue by richard457** [electron/electron-api-demos#334]
* What operating system are you using? window
* What version of Node.js is on your system?v6.11.4
Hello I know how to package app and generate .exe installation file but I have one remaining equation how  to generate a set up model that you click next to accept terms etc... just like normal desktop application how they are being installed. thank you any help tutorial or anything that can be of useful please help me.

**Comment by richard457** [comment]
![Uploading Capture.PNG…](that is the example)

**Comment by kushalausula** [comment]
Use inno setup which is free.

**Comment by shiftkey** [comment]
I would recommend looking at `electron-builder` and the options it supports - [NSIS](https://www.electron.build/configuration/nsis) seems to support various configuration options for the generated installer.
