### ISSUE TITLE
if you drag drop urls on the window it takes you there

### ISSUE THREAD

**Issue by juanefec** [electron/electron-api-demos#337]
* What operating system are you using? 
* What version of Node.js is on your system?
Windows 10 , node 7.9.0

I though that u didnt realize but then i opened Postman to try it there but it didnt work so maybe its intended to be like this

**Comment by marlboro15005** [comment]
Could this be explained in an easier way to understand, so I know why I am receiving emails about this particular conversation?

**Comment by codebytere** [comment]
Please explain more clearly what is happening in this issue.

**Comment by juanefec** [comment]
You execute the example and if you select a URL and draggit into the
electron example window it loads the URL that you dropped and for example,
you can browse YouTube... Just like a chrome tab would do.

**Comment by codebytere** [comment]
We didn't specifically guarded against this, but thanks for bringing it to our attention!
