### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by Clifra-Jones** [electron/electron-api-demos#338]
* What operating system are you using? 
Windows 10 64-bit
* What version of Node.js is on your system?
v8.9.4

Very disconcerting when I am very interested in using Electron that this demo just does not work for me. I get the following errors when executing npm install

npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\optimist-df9079ec\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\wordwrap-a278a778\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-eb0e72c5\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\optimist-df9079ec\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\wordwrap-a278a778\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-eb0e72c5\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\optimist-df9079ec\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\wordwrap-a278a778\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-eb0e72c5\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\optimist-df9079ec\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\wordwrap-a278a778\README.markdown'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-eb0e72c5\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-eb0e72c5\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-802d620b\lib\copy-sync\copy-file-sync.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\deglob-b207452f\test\playground\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-802d620b\lib\copy-sync\copy-sync.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\deglob-b207452f\test\playground\blah.txt'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\fs-extra-802d620b\lib\copy-sync\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\deglob-b207452f\test\playground\custom-gitignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\utile-37125723\test\fixtures\read-json-file\config.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\deglob-b207452f\test\playground\ignored-by-git.txt'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\deglob-b207452f\test\playground\ignored-by-package-json.txt'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\cwilliams\workspace\electron-api-demos\node_modules\.staging\mocha-27b9d74e\bin\_mocha'

They go on for quite more.

**Comment by shiftkey** [comment]
This seems to be a NPM issue rather than related to the app itself.

Could you try running a `git clean -xdf .` to cleanup the `node_modules` folder and then run `npm install` again?

**Comment by Clifra-Jones** [comment]
no joy same errors.

**Comment by Clifra-Jones** [comment]
More Info
NPM version 5.6.0

Centos 7.4:
cwilliams@BBIIUS.NET@bbii2370-nix electron-api-demos]$ npm installnpm ERR! Linux 3.10.0-693.11.6.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY

npm ERR! unable to get local issuer certificate
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cwilliams@BBIIUS.NET/workspace/electron-api-demos/npm-debug.log

Koroa 26 (Fedora)
[09:16 admin ~/Workspace/electron-api-demos (master)]$ npm install
npm ERR! fetch failed https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-2.6.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-2.6.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403

[09:17 admin ~/Workspace/electron-api-demos (master)]$ npm set strict-ssl false
[09:17 admin ~/Workspace/electron-api-demos (master)]$ npm install
npm ERR! fetch failed https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-2.6.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-2.6.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed https://registry.npmjs.org/electron-winstaller/-/electron-winstaller-2.6.3.tgz
npm ERR! Linux 4.13.16-202.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10

npm ERR! fetch failed with status code 403
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/Workspace/electron-api-demos/npm-debug.log

So 3 different OS and cannot get this to install.

**Comment by Clifra-Jones** [comment]
OK fixed on Centos 7.4 with 
npm set strict-ssl=false
(we have SSL intercept on our securioty devices. It sucks)

Still getting errors on Windows and Fedora.

The electron-quick-start works on wall platforms.

**Comment by Clifra-Jones** [comment]
OK, now, sorry for all of this but I have tracted it down to our inline security device blocking some of the URL you are puloling code from. I will continue testing from my personal internet and not in my office.

This is much easier that trying to get the URLs unblocked.
