### ISSUE TITLE
Error running api demp app.

### ISSUE THREAD

**Issue by eddyizm** [electron/electron-api-demos#351]
* What operating system are you using? 
Microsoft Windows 7 [Version 6.1.7601]
* What version of Node.js is on your system?
v8.9.4

## errors from terminal

C:\Users\ecervantes\source\repos\electron-api-demos>npm install
npm WARN tar EPERM: operation not permitted, open 'C:\Users\ecervantes\source\re
pos\electron-api-demos\node_modules\.staging\spectron-728fc1ed\bin\launcher.exe'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ecervantes\AppData\Roaming\npm-cache\_logs\2018-02-28T17_1
4_49_230Z-debug.log

### log attached:   

[2018-02-28T17_14_49_230Z-debug.log](https://github.com/electron/electron-api-demos/files/1768102/2018-02-28T17_14_49_230Z-debug.log)

**Comment by andreacw5** [comment]
This error is generated by npm not by this app. 
See that page for help: [npm ERR cb() never called](https://stackoverflow.com/questions/15393821/npm-err-cb-never-called) or see npm issues on github [here](https://github.com/npm/npm/issues/17839).
 I hope this will help you.

**Comment by eddyizm** [comment]
Thanks for your reply. I'm not very familiar with npm so that makes sense. :-)
