### ISSUE TITLE
Any chance of updating to newer version of chromium?

### ISSUE THREAD

**Issue by mikeliucc** [electron/electron-api-demos#377]
* What operating system are you using? 

I'm using both Mac High Sierra and Windows 10 

* What version of Node.js is on your system?

Hi, I'm working on automating an in-house electron app. As a practice (and waiting for development to finish), I thought I'd try things out with the awesome Electron API Demo.  I'm using Selenium 3/Java. So far so good.

Recently I have just updated to a newer version of chromedriver (2.40) - this is the 'thing' that controls chrome browser and chromium apps - and was quickly greeted with the following error when running my Selenium script:

unknown error: DevToolsActivePort file doesn't exist

Did some research, asked around, yada yada... Finally I decided to file an issue with the food folks at Chromedriver team:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2489#c7

You can read about their comments if you like. In short I think perhaps the chromium that's shipped with this electron app might be a bit outdated. 

Hence I'd like to humbly ask if it'd be possible to upgrade the enclosed chromium (of Electron API Demo) to a more recent version.

Sorry if that's not possible. Thank you for your time!

**Comment by MarshallOfSound** [comment]
@mikeliucc You shouldn't be using the normal chromedriver, rather the binaries we ship in the `electron-chromedriver` package.  Otherwise you will find incompatibilities like this.

**Comment by mikeliucc** [comment]
Thank you for your reply. 

Looks to me that electron-chromedriver is a node module. Is there something suitable for other languages, such as Java?

**Comment by MarshallOfSound** [comment]
@mikeliucc `electron-chromedriver` literally is just a downloader for the chromedriver's we build and ship with our releases.

E.g. See the `2.0.0` release --> https://github.com/electron/electron/releases/tag/v2.0.0

There is a chromedriver zip file for every platform/arch we support

**Comment by mikeliucc** [comment]
ah.. got it! 

I tried with the chromedriver from 2.0.4, and it works great! Thank you!!!

**Comment by marlboro15005** [comment]
Unsub
