### ISSUE TITLE
CLI doesn't work yet

### ISSUE THREAD

**Issue by zeke** [electron/electron-api-demos#385]
So, #378 landed and I published the module to npm:

```
$ npm publish
+ electron-api-demos@1.5.0
```

But the new CLI doesn't work because `electron` is currently a `devDependency`:

```
$ npx electron-api-demos
Cannot find module 'electron'
```

So the question is: should we move `electron` (and probably some other deps too) into `dependencies` to make this work? I wonder what effect this would have on the packaged version of the app.. :thinking:

@codebytere @MarshallOfSound

**Comment by MarshallOfSound** [comment]
`electron-packager` will strip the `electron` module from the packaged app even if you put it in `dependencies` so it should be ok to put it there if you want it to be `npm` installable

**Comment by malept** [comment]
> `electron-packager` will strip the `electron` module from the packaged app even if you put it in `dependencies` so it should be ok to put it there if you want it to be `npm` installable

This is true, however Packager will [also emit a warning](https://github.com/electron-userland/electron-packager/blob/cff971345b0aaef875361fa0ca5d06a297367d03/prune.js#L46-L49) because it's not the Recommended Way:tm: :smile:

**Comment by codebytere** [comment]
@zeke i believe this can be closed with the latest release?

**Comment by zeke** [comment]
Does `npx electron-api-demos` work for you?

I see this:

```
$ npx electron-api-demos
Cannot find module 'electron'
```

...but it happens so fast that I think it must be cached. I don't immediately see how to clear the npx cache.

**Comment by malept** [comment]
`npx --ignore-existing electron-api-demos` doesn't work either 😕

**Comment by malept** [comment]
Ah, 1.5.1 hasn't been released to NPM.

**Comment by codebytere** [comment]
@malept whoops haha i'll take care of that today!

**Comment by codebytere** [comment]
It does now!

**Comment by zeke** [comment]
🤘 Thanks for following through on this @codebytere
