### ISSUE TITLE
Shows an error by App Start "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by saxc** [electron/electron-api-demos#388]
* What operating system are you using? 
macOS 10.13.6

* What version of Node.js is on your system?
V8.11.3

By starting the app is directly shows an Error Message. 
Application Version V1.5.1 (electron-api-demos-mac.zip).

![error](https://user-images.githubusercontent.com/7613585/43685621-b135f378-98b6-11e8-8bd7-672b0bcf3ed1.png)

**Comment by Jianan-Li** [comment]
Seeing the same error here with Application Version V1.5.1 (electron-api-demos-mac.zip).

- What operating system are you using?
macOS 10.14 beta

- What version of Node.js is on your system?
v10.7.0

**Comment by majorcode** [comment]
Seeing the same error here with Application Version V1.5.1 (electron-api-demos-mac.zip).

What operating system are you using?
macOS 10.13.6

What version of Node.js is on your system?
v10.9.0

**Comment by BSVogler** [comment]
Also had an issue. Second run worked.

**Comment by dajomu** [comment]
Did you have to allow the application to run first? It seems like something to do with that affects the process and causes it to crash, but on the next run it is fine.

**Comment by BSVogler** [comment]
Probably.

> Did you have to allow the application to run first? It seems like something to do with that affects the process and causes it to crash, but on the next run it is fine.

**Comment by saxc** [comment]
What operating system are you using?
macOS 10.14

What version of Node.js is on your system?
V10.11.0

I have test this again by a newer os and node version.
For the first open i must right click and click on open, confirm the popup Window for start the application. The error message com up.

After then i can start the Application by double click or right click -> open. Always is showing the Error message.

**Comment by codebytere** [comment]
Should be fixed in latest release.
