### ISSUE TITLE
Cli npm run package ,prompt need enter password?

### ISSUE THREAD

**Issue by yangjunfocus** [electron/electron-api-demos#389]
* What operating system are you using? 
windows 10
* What version of Node.js is on your system?
node v8.10.0

**Comment by Nekores** [comment]
I am using macOS High Sierra Version 10.13.6 (17G65)
Node Version is 10.7.0

I have installed it with the same way and it is working perfectly on my end.

Lemme know if i can help you any?

**Comment by bingyun123** [comment]
Hello Nekores,
run  command : npm run package:sign-exe

![image](https://user-images.githubusercontent.com/30248969/44451152-7911a380-a625-11e8-9033-96a0f4a39fbe.png)
@Nekores   @yangjunfocus

**Comment by codebytere** [comment]
Users of this repo cannot package it themselves as it requires our signing certs. You are, however, welcome to run it from the command line with `npx electron-api-demos` or `npm i -g electron-api-demos`.
