### ISSUE TITLE
 yarn run package:mac

### ISSUE THREAD

**Issue by yangjunfocus** [electron/electron-api-demos#390]
* What operating system are you using? 
Windows 
* What version of Node.js is on your system?
v8.10.0

` yarn run package:mac
yarn run v1.9.4
$ electron-packager . --overwrite --platform=darwin --arch=x64 --out=out --icon=assets/app-icon/mac/app.icns --osx-sign.identity='Developer ID Application: GitHub' --extend-info=assets/mac/info.plist
Cannot create symlinks (on Windows hosts, it requires admin privileges); skipping darwin platform
Done in 7.14s.`
i can't packager Mac, why is that?

**Comment by MarshallOfSound** [comment]
macOS app packages internally have a bunch of symlinks, windows does not support symlinking in the way that POSIX systems (including macOS) do so you can't package mac apps on windows.
