### ISSUE TITLE
how to use crashReporter

### ISSUE THREAD

**Issue by zhangxy1035** [electron/electron-api-demos#405]
I want to use electron crashReporter to Collect errors locally,I saw the electron api,but i do not know how to use it.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by zhangxy1035** [comment]
ok,thinks,i got it
