### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ThaYoMin** [electron/electron-api-demos#414]
* What operating system are you using?  Win 10
* What version of Node.js is on your system?  5.6.0

In the file nav.js at the first line:
`const settings = require('electron-settings)`
prompts "Uncaught ReferenceError: require is not defined" when executed the program.

How can this be solved?
Thanks in advance

**Comment by JohnMLarkin** [comment]
The default setting for nodeIntegration changed from true in versions of Electron prior to 5 to the false.  When creating a BrowserWindow you now need to add the option webPreferences: {nodeIntegration: true}.  This change was made in electron-api-demos at https://github.com/electron/electron-api-demos/commit/419b57b03d15e65332c516b798cbb2a83548ec6c.

**Comment by ThaYoMin** [comment]
Thank you so much.

**Comment by YangYongAn** [comment]
Why does my code still report the error under the correct settings?
![image](https://user-images.githubusercontent.com/4987317/119626618-ffdeb500-be3d-11eb-8d18-3a74d49abf86.png)

![image](https://user-images.githubusercontent.com/4987317/119626681-0e2cd100-be3e-11eb-82c8-1ada0fecf660.png)
