### ISSUE TITLE
1 vulnerability

### ISSUE THREAD

**Issue by rhasce** [electron/electron-api-demos#418]
latest npm on latest Manjaro all freshly installed today.

Says there is one vulnerabilty and I cannot do the npm install because of it, that is a shame :(

it is low: Regular Expression Denial of Service

**Comment by mvmthecreator** [comment]
its in the braces package. have you solved it?

**Comment by kedar-joshi** [comment]
The vulnerability comes from a package called (check-for-leaks)[https://github.com/zeke/check-for-leaks] which hasn't been updated for two years.
