### ISSUE TITLE
Installer Not Making Start Menu or Desktop Shortcuts

### ISSUE THREAD

**Issue by VladPutinEu** [electron/electron-api-demos#483]
* What operating system are you using?
Windows 10 Home 20H2

* What version of Node.js is on your system?
Node.js 14.15.3 LTS

The Electron API Demos installer is not making any Start Menu or Desktop shortcuts.

**Comment by 1234567-glitch** [comment]
@VladPutinEu may i work on it?

**Comment by VladPutinEu** [comment]
> @VladPutinEu may i work on it?

What do you mean. Are you asking if you could help me or asking if you could fix the issue?

**Comment by 1234567-glitch** [comment]
Yes thankfully, yes

**Comment by VladPutinEu** [comment]
What are you saying yes at? Will you fix the issue or will you help me?
